name: 'Compile project action'
description: 'Run maven/gradle to compile project'
inputs:
  skip_tests:
    description: 'Skip tests during build'
    required: false
    default: "false"
  quiet:
    description: 'Reduce console output during build'
    required: false
    default: "true"
  maven_settings_file:
    description: 'Relative path to maven settings xml file'
    required: false
    default: "settings.xml"
runs:
  using: docker
  image: Dockerfile