name: 'Determine variables for use by actions/cache'
description: 'Build and publish docker image to github package repository'
runs:
  using: "composite"
  steps:
    - shell: "bash"
      run: |
        # Set variables path based on project build system
        if [[ -f "build.gradle" || -f "build.gradle.kts" ]]; then
          KEY_HASHED_PATH='**/*.gradle*'
          KEY_NAMESPACE='-gradle-'
          CACHED_PATHS='~/.gradle/caches
        ~/.gradle/wrapper'
        elif [[ -f "pom.xml" ]]; then
          KEY_HASHED_PATH='**/pom.xml'
          KEY_NAMESPACE='-maven-'
          CACHED_PATHS='~/.m2/repository'
        elif [[ -f "package-lock.json" ]]; then
          KEY_HASHED_PATH='**/package-lock.json'
          KEY_NAMESPACE='-node-'
          CACHED_PATHS='~/.npm'
        else
          echo 'Unable to determine build system'
          exit 1
        fi

        # Make variables accessible to subsequent workflows
        echo "CACHE_PATHS<<EOF" >> $GITHUB_ENV
        echo "CACHE_PATHS=$CACHED_PATHS" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "CACHE_KEY_HASHED_PATH=$KEY_HASHED_PATH" >> $GITHUB_ENV
        echo "CACHE_KEY_NAMESPACE=$KEY_NAMESPACE" >> $GITHUB_ENV
